name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  checks: write
  pull-requests: write

jobs:
  contracts:
    name: Contracts
    uses: multiversx/mx-sc-actions/.github/workflows/contracts.yml@v3.2.0
    with:
      rust-toolchain: stable
      enable-contracts-size-report: false
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: test coverage with llvm-cov
        run: |
          cargo install cargo-llvm-cov
          cargo llvm-cov --lcov --output-path lcov.info

      - name: Coveralls
        uses: coverallsapp/github-action@v2

  # test-and-coverage:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       folder: ["contracts/game", "contracts/on-chain-claim"]

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Rust
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: nightly-2024-07-25
  #         profile: minimal
  #         components: rustfmt, clippy
  #         override: true

  #     - name: Install cargo-tarpaulin
  #       run: cargo install cargo-tarpaulin

  #     - name: Run tests and generate coverage for ${{ matrix.folder }}
  #       run: |
  #         cd ${{ matrix.folder }}
  #         cargo tarpaulin --out Xml
  #       continue-on-error: true

  #     - name: Upload coverage report
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: coverage-${{ matrix.folder }}
  #         path: ${{ matrix.folder }}/tarpaulin-report.xml
